CREATE USER 'etl'@'myNodered1.lan' IDENTIFIED BY 'FiskarsRul3z';
SET PASSWORD FOR 'etl'@'myNodered1.lan' = PASSWORD('FiskarsRul3z');
GRANT CREATE USER ON *.* TO 'etl'@'myNodered1.lan';
GRANT EVENT ON *.* TO 'etl'@'myNodered1.lan';
GRANT FILE ON *.* TO 'etl'@'myNodered1.lan';
GRANT PROCESS ON *.* TO 'etl'@'myNodered1.lan';
GRANT RELOAD ON *.* TO 'etl'@'myNodered1.lan';
GRANT BINLOG ADMIN ON *.* TO 'etl'@'myNodered1.lan';
GRANT BINLOG MONITOR ON *.* TO 'etl'@'myNodered1.lan';
GRANT BINLOG REPLAY ON *.* TO 'etl'@'myNodered1.lan';
GRANT REPLICATION MASTER ADMIN ON *.* TO 'etl'@'myNodered1.lan';
GRANT REPLICATION SLAVE ADMIN ON *.* TO 'etl'@'myNodered1.lan';
GRANT SLAVE MONITOR ON *.* TO 'etl'@'myNodered1.lan';
GRANT REPLICATION SLAVE ON *.* TO 'etl'@'myNodered1.lan';
GRANT SHOW DATABASES ON *.* TO 'etl'@'myNodered1.lan';
GRANT SHUTDOWN ON *.* TO 'etl'@'myNodered1.lan';
GRANT SUPER ON *.* TO 'etl'@'myNodered1.lan';
GRANT CREATE TABLESPACE ON *.* TO 'etl'@'myNodered1.lan';
GRANT SET USER ON *.* TO 'etl'@'myNodered1.lan';
GRANT FEDERATED ADMIN ON *.* TO 'etl'@'myNodered1.lan';
GRANT CONNECTION ADMIN ON *.* TO 'etl'@'myNodered1.lan';
GRANT READ_ONLY ADMIN ON *.* TO 'etl'@'myNodered1.lan';
GRANT GRANT OPTION ON *.* TO 'etl'@'myNodered1.lan';
